config/routes.rb
Rails.application.routes.draw do
  root "venues#index"
  resources :venues
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

	def index
		# @test = "testing"
		@venues= Venue.all
	end

	def new
		@venues= Venue.new
	end

	def create
	 @venue = Venue.new(venue_params)
	 if @venue.save
	 	flash[:success] = "Thanks for adding a new venue!"
	 else
	 	flash[:error] = "Sorry, that didn't work - please try again"
	 	render :new
	 end
	 redirect_to root_path
	end

private
	def venue_params
	    params.require(:venue).permit(:name, :address, :latitude, :longitude)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Appetite</title>
		<%= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header>
      <h1>
        <%= link_to "Appetite", root_path %>
      </h1>

      <nav>
        
      </nav>

    </header>

      
    <article>

      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </article>

	</body>
</html>

app/views/venues/index.html.erb
<ul>
<% @venues.each do |v| %>

  <li>
  	<p><%= v.name %></p>
 	<p><%= v.address %></p>
 </li>

<% end %>
</ul>

<section id="map"></section>

<%= link_to "Submit new", new_venue_path, class: 'button' %>

app/views/venues/new.html.erb
<%= simple_form_for @venues do |f| %>

	<%= f.input :name %>
	<%= f.input :address %>
	<%= f.input :latitude %>
	<%= f.input :longitude %>

	<%= f.button :submit, "Add a venue" %>

<% end %>